const CustomerData = [
    {
      "id": 1,
      "name": "Leanne Graham",
      "username": "Bret",
      "location": "New york, USA",
      "order":0,
      "spent": "00",
      "email": "Sincere@april.biz",
      "phone": "1-770-736-8031 x56442",
      "date": "Jun 15, 2022",
      "paymentMode": "Receied",
      "Status": "On hold",
      "description": "Hello, I am new to dev team",
      "image": "https://material-kit-pro-react.devias.io/static/mock-images/avatars/avatar-carson_darrin.png"
    },
    {
      "id": 2,
      "name": "Ervin Howell",
      "username": "Antonette",
      "location": "California, USA",
      "order":0,
      "spent": "300",
      "email": "Shanna@melissa.tv",
      "phone": "010-692-6593 x09125",
      "date": "Jun 20, 2022",
      "paymentMode": "Payment Sent",
      "Status": "Success",
      "description": "Thank you for your quickly response",
      "image": "https://material-kit-pro-react.devias.io/static/mock-images/avatars/avatar-carson_darrin.png"
    },
    {
      "id": 3,
      "name": "Clementine Bauch",
      "username": "Samantha",
      "location": "Georgia, USA",
      "order":3,
      "spent": "500",
      "email": "Nathan@yesenia.net",
      "phone": "1-463-123-4447",
      "date": "Jun 17, 2022",
      "paymentMode": "Receied",
      "Status": "Success",
      "description": "Thank you for your quickly response",
      "image": "https://material-kit-pro-react.devias.io/static/mock-images/avatars/avatar-carson_darrin.png"
    },
    {
      "id": 4,
      "name": "Patricia Lebsack",
      "username": "Karianne",
      "location": "California, USA",
      "order":2,
      "spent": "500",
      "email": "Julianne.OConner@kory.org",
      "phone": "493-170-9623 x156",
      "date": "Jun 17, 2022",
      "paymentMode": "Received",
      "Status": "Success",
      "description": "Can you send updated files ?",
      "image": "https://material-kit-pro-react.devias.io/static/mock-images/avatars/avatar-carson_darrin.png"
    },
    {
      "id": 5,
      "name": "Chelsey Dietrich",
      "username": "Kamren",
      "location": "California, USA",
      "order":0,
      "spent": "00",
      "email": "Lucio_Hettinger@annie.ca",
      "phone": "(254)954-1289",
      "date": "Jun 18, 2022",
      "paymentMode": "Sent",
      "Status": "fail",
      "description": "Can you send updated files ?",
      "image": "https://material-kit-pro-react.devias.io/static/mock-images/avatars/avatar-carson_darrin.png"
    },
    {
      "id": 6,
      "name": "Mrs. Dennis Schulist",
      "username": "Leopoldo_Corkery",
      "location": "Georgia, USA",
      "order":4,
      "spent": "100",
      "email": "Karley_Dach@jasper.info",
      "phone": "1-477-935-8478 x6430",
      "date": "Jun 20, 2022",
      "paymentMode": "Received",
      "Status": "Success",
      "description": "we will start the work",
      "image": "https://material-kit-pro-react.devias.io/static/mock-images/avatars/avatar-carson_darrin.png"
    },
    {
      "id": 7,
      "name": "Kurtis Weissnat",
      "username": "Elwyn.Skiles",
      "location": "Georgia, USA",
      "order":2,
      "spent": "300",
      "email": "Telly.Hoeger@billy.biz",
      "phone": "210.067.6132",
      "date": "Jun 22, 2022",
      "paymentMode": "Sent",
      "Status": "Success",
      "description": "we will start the work",
      "image": "https://material-kit-pro-react.devias.io/static/mock-images/avatars/avatar-carson_darrin.png"
    },
    {
      "id": 8,
      "name": "Nicholas Runolfsdottir V",
      "username": "Maxime_Nienow",
      "location": "New york, USA",
      "order":0,
      "spent": "00.00",
      "email": "Sherwood@rosamond.me",
      "phone": "586.493.6943 x140",
      "date": "Jun 17, 2022",
      "paymentMode": "Received",
      "Status": "Success",
      "description": "Please respond..",
      "image": "https://material-kit-pro-react.devias.io/static/mock-images/avatars/avatar-carson_darrin.png"
    },
    {
      "id": 9,
      "name": "Glenna Reichert",
      "username": "Delphine",
      "location": "New york, USA",
      "order":6,
      "spent": "2000",
      "email": "Chaim_McDermott@dana.io",
      "phone": "(775)976-6794 x41206",
      "date": "Jun 23, 2022",
      "paymentMode": "Sent",
      "Status": "fail",
      "description": "we will start the work",
      "image": "https://material-kit-pro-react.devias.io/static/mock-images/avatars/avatar-carson_darrin.png"
    },
    {
      "id": 10,
      "name": "Clementina DuBuque",
      "username": "Moriah.Stanton",
      "location": "New york, USA",
      "order":10,
      "spent": "10000",
      "email": "Rey.Padberg@karina.biz",
      "phone": "024-648-3804",
      "date": "Jun 17, 2022",
      "paymentMode": "Received",
      "Status": "Success",
      "description": "Thank you",
      "image": "https://material-kit-pro-react.devias.io/static/mock-images/avatars/avatar-carson_darrin.png"
    }
  ];

  export default CustomerData;